# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-12-01 23:22
from __future__ import unicode_literals

from django.db import migrations, models
import queued_storage.backends


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='uploaded_file',
            field=models.FileField(storage=queued_storage.backends.QueuedOverwriteFileStorage(), upload_to=b'uploads'),
        ),
    ]
